version: '3.3'
# ---
services:
  sonar:
    image: sonarqube:8.4-community
    container_name: codaqube-sonar
    networks:
      - codaqube-sonar-network
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonardb:5432/sonarqube
      - SONAR_JDBC_USERNAME=${SONAR_DB_USERNAME}
      - SONAR_JDBC_PASSWORD=${SONAR_DB_PASSWORD}

  sonardb:
    image: postgres
    container_name: codaqube-sonardb
    networks:
      - codaqube-sonar-network
    ports:
      - "5432:5432"
    volumes:
      - sonardb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=${SONAR_DB_USERNAME}
      - POSTGRES_PASSWORD=${SONAR_DB_PASSWORD}

networks:
  codaqube-sonar-network:

volumes:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  sonardb_data:
